WITH PARENT_PROJECT AS
	(SELECT HP.ID,
			P.ID AS PROJECT_ID,
			P.NAME AS PROJECTS,
			P.PARENT_PROJECT_ID,
			PP.NAME AS PARENT_PROJECTS
		FROM PROJECTS P
		LEFT JOIN PROJECTS PP ON P.PARENT_PROJECT_ID = PP.ID
		LEFT JOIN HIST_PROJECTS HP ON P.ID = HP.PROJECT_ID),
-- 	USER_DETAILS AS
-- 	(SELECT _USERS.ID AS USER_ID,
-- 			_USERS.SYSTEM_USER_ID,
-- 			_SYSTEM_USERS.NAME,
-- 			_SYSTEM_USERS.FRIENDLY_NAME,
-- 			_USERS.LICENSING_ROLE_ID,
-- 			_USERS.LICENSING_ROLE_NAME,
-- 			_SITES.NAME AS SITE,
-- 			CASE
-- 							WHEN _SYSTEM_USERS.ADMIN_LEVEL = 5 THEN 'Site Administrator'
-- 							WHEN _SYSTEM_USERS.ADMIN_LEVEL = 10 THEN 'Server Administrator'
-- 							ELSE _USERS.LICENSING_ROLE_NAME
-- 			END AS CORRECTROLES
-- 		FROM _USERS
-- 		LEFT JOIN _SYSTEM_USERS ON _USERS.SYSTEM_USER_ID = _SYSTEM_USERS.ID
-- 		LEFT JOIN _SITES ON _USERS.SITE_ID = _SITES.ID
-- 		ORDER BY _SYSTEM_USERS.FRIENDLY_NAME),
	FINAL_DETAILS AS
	(SELECT HS.NAME AS SITE,
			COALESCE(PP.PARENT_PROJECTS,

				'No Parent Projects') AS PARENT_PROJECTS,
			COALESCE(PP.PROJECTS,

				'No Projects') AS PARENT_PROJECTS,
			PP.PROJECTS,
			HP.NAME AS PROJECT,
			HE.HIST_WORKBOOK_ID,
			HW.NAME AS WORKBOOK,
			HU.SYSTEM_USER_ID,
			HE.HIST_ACTOR_USER_ID,
			HU.NAME AS USER,
			SR.NAME AS ROLE_NAME,
			SR.DISPLAY_NAME AS CORRECT_ROLE,
	 		HE.CREATED_AT,
			HE.HISTORICAL_EVENT_TYPE_ID,
			HET.NAME,
			HET.ACTION_TYPE,
			HET.NAME AS ACTION_SUBTYPE
		FROM HISTORICAL_EVENTS HE
		LEFT JOIN HISTORICAL_EVENT_TYPES HET ON HE.HISTORICAL_EVENT_TYPE_ID = HET.TYPE_ID
		LEFT JOIN HIST_WORKBOOKS HW ON HE.HIST_WORKBOOK_ID = HW.ID
		LEFT JOIN HIST_USERS HU ON HE.HIST_ACTOR_USER_ID = HU.ID
		LEFT JOIN HIST_PROJECTS HP ON HE.HIST_PROJECT_ID = HP.ID
		LEFT JOIN HIST_SITES HS ON HE.HIST_ACTOR_SITE_ID = HS.ID
		LEFT JOIN PARENT_PROJECT PP ON HE.HIST_PROJECT_ID = PP.ID
-- 		LEFT JOIN USER_DETAILS UD ON HU.SYSTEM_USER_ID = UD.SYSTEM_USER_ID
		LEFT JOIN SITE_ROLES SR ON HU.SITE_ROLE_ID = SR.ID)
		
		select * from FINAL_DETAILS
		
-- 		select * from SITE_ROLES