WITH PROJECT_HIERARCHY AS
	(SELECT P1.ID AS PROJECT_ID,
			P1.NAME AS PROJECT_NAME,
			COALESCE(P1.CONTROLLING_PERMISSIONS_PROJECT_ID,

				P1.ID) AS CONTROL_PROJECT_ID,
			COALESCE(P2.NAME,

				P1.NAME) AS CONTROL_PROJECT_NAME,
			P1.PARENT_PROJECT_ID,
			COALESCE(P3.NAME,

				P2.NAME,
				P1.NAME) AS PARENT_PROJECT
		FROM PROJECTS P1
		LEFT JOIN PROJECTS P2 ON P1.CONTROLLING_PERMISSIONS_PROJECT_ID = P2.ID
		LEFT JOIN PROJECTS P3 ON P1.PARENT_PROJECT_ID = P3.ID),
	EVENT_SUMMARY AS
	(SELECT -------------------------------
-- Event Details summary
HE.HISTORICAL_EVENT_TYPE_ID,
			HET.NAME AS EVENT_TYPE,
			HET.ACTION_TYPE, -------------------------------
-- Day time this is used
HE.CREATED_AT, -------------------------------
--user who initiated action
HE.HIST_ACTOR_USER_ID,
			HU.SYSTEM_USER_ID AS USER_ID,
			HU.NAME AS USER_NAME, -------------------------------
--Project Details
HE.HIST_PROJECT_ID,
			HP.PROJECT_ID,
			HP.NAME AS PROJECT_NAME, -------------------------------
--PROJECT_HIERARCHY details
PH.PROJECT_ID AS PROJECT_ID_H,
			PH.PROJECT_NAME AS PROJECT_NAME_H,
			PH.CONTROL_PROJECT_ID,
			PH.CONTROL_PROJECT_NAME,
			PH.PARENT_PROJECT_ID,
			PH.PARENT_PROJECT, -------------------------------
--Workbook details
HE.HIST_WORKBOOK_ID,
			HW.WORKBOOK_ID,
			HW.NAME AS WORKBOOK_NAME, --------------------------------
--View details
HE.HIST_VIEW_ID,
			HV.VIEW_ID,
			HV.NAME AS VIEW_NAME, --------------------------------
--Connected datasource
HE.HIST_DATASOURCE_ID,
			HD.DATASOURCE_ID,
			HD.NAME AS DATASOURCE_NAME 
---------------------------------
--userful for the future
-- he.hist_group_id,
-- he.hist_licensing_role_id,
-- he.hist_data_connection_id,
-- he.hist_capability_id
---------------------------------

		FROM HISTORICAL_EVENTS HE
		LEFT JOIN HISTORICAL_EVENT_TYPES HET ON HE.HISTORICAL_EVENT_TYPE_ID = HET.TYPE_ID
		LEFT JOIN HIST_USERS HU ON HE.HIST_ACTOR_USER_ID = HU.ID
		LEFT JOIN HIST_PROJECTS HP ON HE.HIST_PROJECT_ID = HP.ID
		LEFT JOIN HIST_WORKBOOKS HW ON HE.HIST_WORKBOOK_ID = HW.ID
		LEFT JOIN HIST_VIEWS HV ON HE.HIST_VIEW_ID = HV.ID
		LEFT JOIN HIST_DATASOURCES HD ON HE.HIST_DATASOURCE_ID = HD.ID
		LEFT JOIN PROJECT_HIERARCHY PH ON HP.PROJECT_ID = PH.PROJECT_ID) 
SELECT * FROM EVENT_SUMMARY WHERE CREATED_AT>=current_date - interval '91 days'
LIMIT 100

