	WITH PROJECT_HIERARCHY AS (
  SELECT 
    P1.ID AS PROJECT_ID, 
    P1.NAME AS PROJECT_NAME, 
    COALESCE(
      P1.CONTROLLING_PERMISSIONS_PROJECT_ID, 
      P1.ID
    ) AS CONTROL_PROJECT_ID, 
    COALESCE(P2.NAME, P1.NAME) AS CONTROL_PROJECT_NAME, 
    P1.PARENT_PROJECT_ID, 
    COALESCE(P3.NAME, P2.NAME, P1.NAME) AS PARENT_PROJECT 
  FROM 
    PROJECTS P1 
    LEFT JOIN PROJECTS P2 ON P1.CONTROLLING_PERMISSIONS_PROJECT_ID = P2.ID 
    LEFT JOIN PROJECTS P3 ON P1.PARENT_PROJECT_ID = P3.ID
)
select 	
	
	CASE 
  		WHEN PH.PROJECT_NAME = PH.PARENT_PROJECT AND PH.PROJECT_NAME = PH.CONTROL_PROJECT_NAME THEN
    		E'\\' || PH.CONTROL_PROJECT_NAME||'\'
  		WHEN PH.PROJECT_NAME = PH.PARENT_PROJECT THEN
    		E'\\' || PH.CONTROL_PROJECT_NAME || '\' || PH.PROJECT_NAME||'\'
		WHEN PH.CONTROL_PROJECT_NAME = PH.PARENT_PROJECT THEN
    		E'\\' || PH.CONTROL_PROJECT_NAME || '\' || PH.PROJECT_NAME||'\'
  		ELSE
    		E'\\' || PH.CONTROL_PROJECT_NAME || '\' || PH.PARENT_PROJECT || '\' || PH.PROJECT_NAME
		END AS PROJECT_PATH,